config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'visitors#index'
  resources :users
  resources :sessions, only: [:new, :create, :delete]
  resources :players

  resources :games, only: [:index]

  get "/games/:game_id/players/:player_id/decline", to: 'players#decline'
  get "/games/:game_id/players/:player_id/confirm", to: 'players#confirm'
  get "/teams/:team_id/players/:player_id/core", to: 'players#core'

  get "teams/:team_id/players/:id/remove", to: 'players#remove'

  get "/teams/:team_id/games/:game_id/notify", to: 'games#notify'

  resources :teams do
    resources :games
    resources :rosters, only: [:create, :delete]
  	resources :players
  end


  # get 'twilio/voice' => 'twilio#trigger_sms_alerts'
  post 'twilio/voice' => 'twilio#response_message'



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :teams
  has_many :games, through: :teams
  has_many :players, through: :teams

  def upcoming_games
  	 games.where("time > ?", Date.today).order(time: 'ASC').limit(5)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    redirect_to user_path(current_user)
  end

  def show
    @user = User.find(params[:id])
    @games = current_user.upcoming_games
    unless @user == current_user
      redirect_to root_path, :alert => "Access denied."
    end
  end

end

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="content">

	<h1>Hi, <%= current_user.name %></h1>

		<%= link_to "Add Team", new_team_path, class: 'new-team-btn' %>
		<%= link_to "View Games", games_path, class: 'view-games-btn' %>

	<div class="teams-list-container">
		<h2>Your Teams:</h2>
		<ul>
			<% current_user.teams.each do |team| %>
				<li>
					<span class="team-names"><%= link_to team.name, team %></span>
					<span class="team-modifiers"><%= link_to "+ player", new_team_player_path(team) %></span>
					<span class="team-modifiers"><%= link_to "+ game", new_team_game_path(team) %></span>
				</li>
			<% end %>
		</ul>
	</div>

	<div class="upcoming-games-container">
		<h2>Upcoming Games:</h2>
		<ul>
			<%= render partial: "games/listitem", collection: @games %>
		</ul>
	</div>

</div>