config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'visitors#index'
  resources :users
  resources :sessions, only: [:new, :create, :delete]
  resources :players

  resources :games, only: [:index]

  get "/games/:game_id/players/:player_id/decline", to: 'players#decline'
  get "/games/:game_id/players/:player_id/confirm", to: 'players#confirm'
  get "/teams/:team_id/players/:player_id/core", to: 'players#core'

  get "teams/:team_id/players/:id/remove", to: 'players#remove'

  get "/teams/:team_id/games/:game_id/notify", to: 'games#notify'

  resources :teams do
    resources :games
    resources :rosters, only: [:create, :delete]
  	resources :players
  end


  # get 'twilio/voice' => 'twilio#trigger_sms_alerts'
  post 'twilio/voice' => 'twilio#response_message'



end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :team
  has_many :players, through: :team
  has_one :captain, through: :team
  has_many :confirmations
  has_many :responded_players, through: :confirmations, source: :player

  validates :location, :time, :opposing_team, :team_id, :players_required, presence: true
  validate :check_full_team

  def check_full_team
    if players_required.to_i <= 0
      errors.add(:players_required, "cannot be less than one.")
    end
  end


  def name
    "#{team.name} vs #{opposing_team}"
  end

  def confirmed_players
    confirms = self.confirmations.where(confirmed: true)
    if confirms.any?
      confirms.map(&:player).flatten
    else
      []
    end
  end

  def declined_players
    declines = self.confirmations.where(confirmed: false)
    if declines.any?
      declines.map(&:player).flatten
    else
      []
    end
  end

  def players_without_confirmations
    all_players = self.players
    all_players -= confirmed_players
    all_players -= declined_players
    p all_players
    all_players
  end

  def full?
    confirmed_players.count >= players_required
  end

  def clean_time
    time.strftime("%l:%M%P %A, %b %e")
  end

  def details
    message = <<-msg
    - #{self.name}
    Location: #{location}
    Time: #{clean_time}
    msg
    message
  end

  def status
    self.details
    # players = confirmed_players.map(&:name).flatten.join(" ")
    # players
  end

end

app/controllers/games_controller.rb
require 'rake'

class GamesController < ApplicationController

  def index
    @games = current_user.upcoming_games
  end

  def show
    @team = Team.find_by(id: params[:team_id])
    @game = Game.find_by(id: params[:id])
  end

  def new
    @team = Team.find_by(id: params[:team_id])
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    @game.time = time_parse
    @game.team_id = params[:team_id]
    @game.home_team = home?

    if @game.save
      redirect_to team_game_path(@game.team, @game)
    else
      @team = Team.find_by(id: params[:team_id])
      render :new
    end
  end

  def notify
    Team.all.each do |team|
      team.games.each do |game|
        next if game.full?
        game.players_without_confirmations.each do |player|
          if Roster.find_by(team: team, player: player).core == true
            # if player.name == 'jordan'
              CreateTwilioClient.new(player.phone_number, game.details).call
            end
        end
      end
    end
    @game = Game.find_by(id: params[:game_id])
    @team = Team.find_by(id: params[:team_id])
    redirect_to team_game_path(@team, @game), notice: "Players have been notified"
  end


  private

  def game_params
    params.require(:game).permit(:location, :opposing_team, :team_id, :players_required)
  end

  def time_parse
    game = params[:game]
    DateTime.new(game['time(1i)'].to_i,game['time(2i)'].to_i,game['time(3i)'].to_i,game['time(4i)'].to_i,game['time(5i)'].to_i,game['time(6i)'].to_i)
  end

  def home?
    params[:game][:home_team] == 0 ? false : true
  end

end

app/views/games/_listitem.html.erb
<li class="game-list-item">
  <%= link_to listitem.name, team_game_path(listitem.team, listitem) %>
  <p>Confirmed Players: <%= listitem.confirmed_players.count %> / <%= listitem.players_required %></p>
  <p><%= listitem.location %></p>
  <p><%= listitem.clean_time %></p>
  <p><%= distance_of_time_in_words(listitem.time, DateTime.now).capitalize %> until game time!</p>
</li>

app/views/games/index.html.erb
<div class="content">
  <h1>Upcoming Games</h1>
  <ul>
    <%= render partial: "games/listitem", collection: @games %>
  </ul>
</div>

app/views/games/new.html.erb
<div class="content">
	<%= link_to "<< Back to Team", team_path(@team) %>
	<h1>Add a new Game for <%= @team.name %></h1>

	<%= form_for [@team, @game], url: team_games_path do |f| %>

		<%= f.label :location %>
		<%= f.text_field :location, value: @team.default_location %>

		<%= f.label :time %>
		<%= f.datetime_select :time, :ampm => true, :minute_step => 15 %>

		<%= f.label :home_game? %>
		<%= f.check_box :home_team %>

		<%= f.label :opposing_team %>
		<%= f.text_field :opposing_team %>

		<%= f.label :players_required %>
		<%= f.text_field :players_required, value: @team.default_required_players %>

		<%= f.submit "Submit" %>

	<% end %>

</div>

app/views/games/show.html.erb
<div class="content">
<%= link_to "<< Back to Team", team_path(@game.team) %>
	<h1><%= @game.name %></h1>
	<ul>
		<li><%= @game.location %></li>
		<li><%= @game.clean_time %></li>
	</ul>

	<%= link_to "Notify Players", "/teams/#{@team.id}/games/#{@game.id}/notify" %>

	<h4>Confirmed Players <%= @game.confirmed_players.count %> / <%= @game.players_required %></h2>
	<ul>
		<% @game.confirmed_players.each do |player| %>
			<li>
				<span class='team-names'><%= link_to player.name, player %></span><span class="core"><%= Roster.find_by(player: player, team: @game.team).core ? 'alternate' : 'core' %></span>
				<span class='team-modifiers'><%= link_to "Decline", "/games/#{@game.id}/players/#{player.id}/decline" %></span>
			</li>
		<% end %>
	</ul>

	<h4>Unconfirmed Players (<%= @game.players_without_confirmations.count %>)</h2>
	<ul>
		<% @game.players_without_confirmations.each do |player| %>
			<li>
				<span class='team-names'><%= link_to player.name, player %></span><span class="core"><%= Roster.find_by(player: player, team: @game.team).core ? 'alternate' : 'core' %></span>
				<span class='team-modifiers'><%= link_to "Confirm", "/games/#{@game.id}/players/#{player.id}/confirm" %></span>
				<span class='team-modifiers'><%= link_to "Decline", "/games/#{@game.id}/players/#{player.id}/decline" %></span>
			</li>
		<% end %>
	</ul>

	<h4>Declined Players (<%= @game.declined_players.count %>)</h2>
	<ul>
		<% @game.declined_players.each do |player| %>
			<li>
				<span class='team-names'><%= link_to player.name, player %></span><span class="core"><%= Roster.find_by(player: player, team: @game.team).core ? 'alternate' : 'core' %></span>
				<span class='team-modifiers'><%= link_to "Confirm", "/games/#{@game.id}/players/#{player.id}/confirm" %></span>
			</li>
		<% end %>
	</ul>


</div>