config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'visitors#index'
  resources :users
  resources :sessions, only: [:new, :create, :delete]
  resources :players

  resources :games, only: [:index]

  get "/games/:game_id/players/:player_id/decline", to: 'players#decline'
  get "/games/:game_id/players/:player_id/confirm", to: 'players#confirm'
  get "/teams/:team_id/players/:player_id/core", to: 'players#core'

  get "teams/:team_id/players/:id/remove", to: 'players#remove'

  get "/teams/:team_id/games/:game_id/notify", to: 'games#notify'

  resources :teams do
    resources :games
    resources :rosters, only: [:create, :delete]
  	resources :players
  end


  # get 'twilio/voice' => 'twilio#trigger_sms_alerts'
  post 'twilio/voice' => 'twilio#response_message'



end

app/models/player.rb
class Player < ApplicationRecord

	has_many :rosters
	has_many :teams, through: :rosters
	has_many :games, through: :teams
  



	validates_presence_of :name, :phone_number
  validate :check_phone_number

  def check_phone_number
    self.phone_number.gsub!(/\D/, "")
    if phone_number.length != 10
      errors.add(:phone_number, "is not a valid number.")
    end
  end

  def core

  end

  def core=(item)

  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def new
    @team = Team.find_by(id: params[:team_id])
    @player = Player.new
  end

  def create
    p params
    p core?

    @player = Player.new(player_params)

    params[:team_id] ? @team = Team.find_by(id: params[:team_id]) : @team = Team.find_by(id: params[:player][:team_ids])

    if @player.save
      Roster.create(team: @team, player: @player, core: core?)
      redirect_to @team, notice: 'Player was successfully created.'
    else
      render :new, errors: @player.errors.full_messages.join(", ")
    end
  end

  def show
    @player = Player.find_by(id: params[:id])
  end

  def edit
    @player = Player.find_by(id: params[:id])
    @team = Team.find_by(id: params[:team_id])
  end

  def update
    @team = Team.find_by(id: params[:team_id])
    @player = Player.find_by(id: params[:id])
    if @player.update(player_params)
      p params
      @roster = Roster.find_or_initialize_by(team: @team, player: @player)
      @roster.core = core?
      @roster.save
      redirect_to @team
    else
      render :edit
    end
  end

  def decline
    @game = Game.find_by(id: params[:game_id])
    @confirmation = Confirmation.find_or_initialize_by(player_id: params[:player_id], game_id: params[:game_id])
    @confirmation.confirmed = false
    @confirmation.save!

    redirect_to team_game_path(@game.team, @game)
  end

  def confirm
    @game = Game.find_by(id: params[:game_id])
    if @game.full?
      redirect_to team_game_path(@game.team, @game), notice: "Game is already full."
    else
      @confirmation = Confirmation.find_or_initialize_by(player_id: params[:player_id], game_id: params[:game_id])
      @confirmation.confirmed = true
      @confirmation.save

      redirect_to team_game_path(@game.team, @game)
    end
  end

  def remove
    @team = Team.find_by(id: params[:team_id])
    @roster = Roster.find_by(team_id: params[:team_id], player_id: params[:id])
    @roster.destroy
    redirect_to @team
  end

  # def core
  #   @player = Player.find_by(id: params[:player_id])
  #   @team = Team.find_by(id: params[:team_id])
  #   @roster = Roster.find_by(team: @team, player: @player)
  #   @roster.core = !@roster.core
  #   @roster.save

  #   redirect_to @team
  # end

  private

  def player_params
    params.require(:player).permit(:name, :phone_number)
  end

  def core?
    params[:player][:core] == '1' ? 'true' : 'false'
  end

end

app/views/players/_form.html.erb
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :phone_number_with_area_code %>
<%= f.text_field :phone_number %>

app/views/players/edit.html.erb
<div class="content">

  <%= form_for [@team, @player], url: team_player_path(@team, @player), method: :patch do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :phone_number_with_area_code %>
    <%= f.text_field :phone_number %>

    <%= f.label :core_player? %>
    <%= f.check_box :core, checked: Roster.find_by(team: @team, player: @player).core %>

    <%= f.submit "Update Player" %>

  <% end %>

</div>

app/views/players/new.html.erb
<div class="content">

  <%= link_to "<< Back to Team", team_path(@team) %>

	<h1>Add a Player to <%= @team.name %></h1><br>

  <p>Enter a new player OR select existing player from drop-down list below.</p>
	<%= form_for [@team, @player] do |f| %>

		<%= f.label :name %>
		<%= f.text_field :name %>

		<%= f.label :phone_number_with_area_code %>
    <%= f.text_field :phone_number %>

    <%= f.label :core_player? %>
    <%= f.check_box :core %>

		<%= f.submit "Add Player" %>

	<% end %>
<hr>
<p>Select existing player:</p>
  <%= form_for Roster.new, url: team_rosters_path do |f| %>

    <%= f.select :player_id, (current_user.players - @team.players).collect { |p| [ p.name, p.id ] }, include_blank: true %>

    <%= f.label :core_player %>
    <%= f.check_box :core %>

    <%= f.submit "Add Player" %>

  <% end %>

</div>

app/views/players/show.html.erb
<div class="content">
  <h1><%= @player.name %>'s Teams:</h1>

  <ul>
    <% @player.teams.each do |team| %>
      <li>
      	<%= link_to team.name, team %>
      </li>
    <% end %>
  </ul>

</div>